name: Build cht-core and test against node versions

on: push

jobs:
  macos:
    name: run on os
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm CI
      run: npm ci
    - name: Run the api
      run: node api/src/services/generate-xform.js

  ubuntu-os:
    name: run on linux
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm CI
      run: npm ci
    - name: Run the api
      run: node api/src/services/generate-xform.js


