name: Build cht-core and test against node versions

on: push

env:
  COUCH_URL: http://admin:pass@localhost:5984/medic-test
  COUCH_NODE_NAME: nonode@nohost
  BUILDS_SERVER: ${{ secrets.AUTH_MARKET_URL && '_couch/builds_testing' || '_couch/builds_external' }}
  STAGING_SERVER: ${{ secrets.AUTH_MARKET_URL && '_couch/builds' || '_couch/builds_external' }}
  MARKET_URL_READ: 'https://staging.dev.medicmobile.org'
  MARKET_URL: ${{ secrets.AUTH_MARKET_URL || 'https://staging.dev.medicmobile.org' }}

jobs:
  build:
    name: Compile the app
    runs-on: ubuntu-18.04

    steps:
    - name: Get Docker Hub username
      id: get-docker-hub-username
      run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: steps.get-docker-hub-username.outputs.dockerhub_username
    - name: Get branch name
      uses: nelonoel/branch-name@1ea5c86cb559a8c4e623da7f188496208232e49f
    - name: Set CI Vars
      run: |
        echo "BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Couch Start
      run: ./scripts/ci/couch-start
    - name: Create logs directory
      run: mkdir tests/logs
    - name: npm CI
      run: npm ci
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: Configure Couch
      run: ./scripts/ci/couch-config
    - name: Grunt CI-Compile
      run: |
        node --stack_size=10000 `which grunt` ci-compile-github
    - name: Publish for testing
      run: |
        node --stack_size=10000 `which grunt` publish-for-testing
  tests:
    needs: build
    name: test installed chrome version
    runs-on: ubuntu-18.04

    steps:
    - name: Get Docker Hub username
      id: get-docker-hub-username
      run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: steps.get-docker-hub-username.outputs.dockerhub_username
    - name: Set CI Vars
      run: |
        echo "BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
        echo "TEST_SUITE=integration" >> $GITHUB_ENV

    - name: Check if chrome driver get installed
      run: node --stack_size=10000 `which grunt` start-webdriver
